nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: []
        allow_methods: []
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
